language: rust
dist: bionic
rust:
  - 1.35.0
cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libcairo2-dev
    - libarchive-dev
    - gir1.2-poppler
    - libpoppler-dev
    - libpoppler-glib-dev
cache:
  directories:
    - $HOME/.rustup
